### ISSUE TITLE
Code for value function clipping 

### ISSUE THREAD

**Issue by NaiveRed** [implementation-matters/code-for-paper#1]
In the paper (sec 2) and description of value function clipping, the PPO-like objective is the **minimum** of clipped and unclipped. However, the code applies the **maximum** of them, does it have different effects from the paper said? 
https://github.com/implementation-matters/code-for-paper/blob/094994f2bfd154d565c34f5d24a7ade00e0c5bdb/src/policy_gradients/steps.py#L89-L96

**Comment by GIS-PuppetMaster** [comment]
Same question here

**Comment by yuanzhi0515** [comment]
Another question here.Why use value function clip before pow(2)?

**Comment by GIS-PuppetMaster** [comment]
> Another question here.Why use value function clip before pow(2)?

Personal opinion, I guess it's the same reason with clip pi, to limit the update step length of critic.

**Comment by yuanzhi0515** [comment]
> > Another question here.Why use value function clip before pow(2)?
> 
> Personal opinion, I guess it's the same reason with clip pi, to limit the update step length of critic.

Thank you!But in the OpenAI baselines ppo code,the value clipping is:
![image](https://user-images.githubusercontent.com/53039803/76383252-2d088a00-6396-11ea-8bdf-39d2240468e5.png)
OpenAI use square(pow(2)) before the max.But in this code,it use max before pow(2):
![image](https://user-images.githubusercontent.com/53039803/76383699-9c32ae00-6397-11ea-8b04-0fbc1c0cec9e.png)

I am confused about it.

**Comment by NaiveRed** [comment]
@yuanzhi0515 
I guess that `pow` is more proper to use before `max`, since `max` may be affected by the neg/pos.

**Comment by andrewilyas** [comment]
Hi all, 

Thanks for raising this issue! Indeed, the ``min`` in the paper is a typo and should be the max, and the pow(2) should be applied first. Both of these are fixed in our official code release, found here: https://github.com/MadryLab/implementation-matters
